def cls():
	print('\n' * 40)
from tkinter import*
window = Tk()
window.title('label example ')
label=Label(window,text ="hi hello welcome")
label.pack(padx = 200,pady = 50)
adjective1 = input("Tell me an adjective, and click enter. ")
noun1 = input("Tell me a noun (plural), and click enter. ")
adjective2 = input("Tell me an adjective, and click enter. ")
noun2 = input("Tell me another noun, and click enter. ")
verb = input("Tell me a verb, and click enter. ")
title =('Welcome to Mad libs Lets start')
cls()
print (title)
print ("There was once a "+ adjective1 +" boy from Dubai" )
print ("who was baked by "+ noun1 + " in a pie")
print (" to his "+ noun2 + "'s " + adjective2 + " disgust ")
print ("he "+ verb +" through the crust")
print ("and exclaimed ,'what a good boy am I !'")
print ("so are you happy with your wacky story!")
